### ISSUE TITLE
create a require and watch_in for shorewall

### ISSUE THREAD

**Issue by p-thurner** [blunix/formula-tinc#4]
one of the first things to be installed is shorewall. however as shorewall == iptables, if interfaces dont exist, rules wont be created. therefore installing tinc after shorewall will fail.

/srv/salt/tinc.sls:
```
# on top of file include shorewall
require:
  - shorewall

# actual formula
some_config_file_state:
  file.managed:
    - name: /etc/tinc/interconnect/tinc.conf
    - watch_in:
      - service: shorewall_service
```

if the tinc config file is changed, the shorewall service will be restarted.
